### ISSUE TITLE
Recommendation: Simplify Dockerfile with variables.

### ISSUE THREAD

**Issue by danbo** [Trauma/docker-minimserver#2]
ie.

ENV version=0.8.4
ENV file=MinimServer-${version}-linux-x64.tar.gz

wget -O /opt/${file}
tar xf $file

**Comment by Trauma** [comment]
I've implemented your recommendation in a slightly different manner: 

```
ENV url=http://jminim.com/cada/MinimServer-0.8.4-linux-x64.tar.gz

RUN wget -O /opt/MinimServer.tar.gz ${url} && \
        cd /opt && \
        tar xf MinimServer.tar.gz && \
        rm MinimServer.tar.gz
```

**Comment by danbo** [comment]
Looks better but you still have MinimServer.tar.gz three times. Ideally that would be in a variable too.

**Comment by Trauma** [comment]
Not so sure since it would add a uneeded layer to the image.
