### ISSUE TITLE
Download URL changed by author.

### ISSUE THREAD

**Issue by danbo** [Trauma/docker-minimserver#5]
ie

http://minimserver.com/downloads/MinimServer-0.8.3d-linux-x64.tar.gz

doesn't work, but 

http://jminim.com/cada/MinimServer-0.8.3d-linux-x64.tar.gz

does.

**Comment by Trauma** [comment]
Unfortunately we can't use ARG option at build time with automated build, so I've decided to use:

ENV url=http://jminim.com/cada/MinimServer-0.8.4-linux-x64.tar.gz
